server:
  port: 8080
  address: localhost
spring:
  rabbitmq:
    addresses: 43.142.32.223:5673
    username: hiiro
    password: 136601
    virtual-host: /test
#  username: guest
#  password: guest
#  virtual-host: /
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 16
      max-active: 32
      min-idle: 8
      timeout: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotori?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 136601
  jwt:
    config:
      key: Vinalla
      ttl: 3600000

  # 线程池
  task:
      pool:
        corePoolSize: 2 # 线程池容量/核心数
        maxPoolSize: 3
        keepAliveSeconds: 60  #非核心线程TTL
        queueCapacity: 20 # 队列容量
  minio:
    endpoint: http://149.88.95.15:9000 #Minio服务所在地址
    bucketName: image #存储桶名称
    accessKey: FCr70ZfLSBaNldfkffvC #访问的key
    secretKey:   #访问的秘钥


